#!/bin/bash

if [ "$STARTUP" ]; then
	URL="$STARTUP"
	echo "STARTUP variable found, using $STARTUP as url instead"
fi

if [ -z "$URL" ]; then
	echo "No url was given. Please use -e URL={url} to set the url to the zip file of foundry."
	exit 1
fi

if [ -r /home/container/current-installed ]; then
	value=$(</home/container/current-installed)
else
	value="none"
fi

if [ "$URL" != $value ]; then
	if [ -d /home/container/temp ]; then
		rm /home/container/temp -rf
	fi

	TMPFILE=/home/container/foundry.zip
	wget "$URL" -O "$TMPFILE"
	echo "Unzipping file"
	unzip -q "$TMPFILE" -d /home/container/temp
	echo "Done unzipping"
	rm "$TMPFILE"

	if [ -d /home/container/app ]; then
		rm /home/container/app -rf
	fi

  mv /home/container/temp/resources/app /home/container/app
	rm /home/container/temp -rf
	
	if [ ! -d /home/container/data ]; then
		mkdir /home/container/data
		chmod -R 774 /home/container/data
	fi

	echo "$URL" > "/home/container/current-installed"
	cd /home/container/app || exit
	npm install --quiet --no-progress
fi

if [ -r /home/container/app/main.js ]; then
  cd /home/container/app || exit
	node main.js --headless --dataPath=/home/container/data
else
	echo "Failed to find main.js"
fi